name: Deploy to production

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t ${{secrets.DOCKER_IMAGE}}:${{github.sha}} . && docker push ${{secrets.DOCKER_IMAGE}}:latest

      - name: Push docker image to dockerhub
        run: docker push ${{secrets.DOCKER_IMAGE}}:${{github.sha}} && docker push ${{secrets.DOCKER_IMAGE}}:latest

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Copy docker-compose
        run: scp .deployment/docker-compose.production.yml ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:/home/${{secrets.SSH_USER}}/composes/mailer/docker-compose.production.yml

      - name: Copy docker_run.sh
        run: scp .deployment/docker_run.sh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:/home/${{secrets.SSH_USER}}/composes/mailer/docker_run.sh

      - name: Run deploy script on server
        run: ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} bash /home/${{secrets.SSH_USER}}/composes/mailer/docker_run.sh '${{secrets.DOCKER_USERNAME}}' '${{secrets.DOCKER_PASSWORD}}' '${{secrets.DOCKER_IMAGE}}' '${{secrets.DOCKER_REGISTRY}}'
